Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-7f418316
    us-west-1:
      AMI: ami-951945d0
    us-west-2:
      AMI: ami-16fd7026
    eu-west-1:
      AMI: ami-24506250
    sa-east-1:
      AMI: ami-3e3be423
    ap-southeast-1:
      AMI: ami-74dda626
    ap-southeast-2:
      AMI: ami-b3990e89
    ap-northeast-1:
      AMI: ami-dcfa4edd
Parameters:
  ImageId:
    Type: String
    Default: ami-0862aabda3fb488b5
  LatestAmiId:
    Type: String
    Default: 'ami-0ce1e3f77cd41957e'
Resources:  
  Ec2Instance: 
      Type: "AWS::EC2::Instance"
      Properties: 
        ImageId: !Ref LatestAmiId
        KeyName: "i88i"
        InstanceType:t2.large
        SecurityGroups:
          -  SSH-WEB
        Tags:
            - Key: Management Mode
              Value: cloudformation
            - Key: with-quotes
              Value: "Yes"
            - Key: No-Quotes
              Value: Yes



